location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive

